# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0002_auto_20170719_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parentmail',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
