# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-25 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0002_auto_20170804_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='Kids Zone is Cool', max_length=40),
        ),
    ]
