# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-26 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0003_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='static/default.png', null=True, upload_to='user_images'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
