# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0011_auto_20170803_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='has_liked',
        ),
        migrations.AddField(
            model_name='commentlikemodel',
            name='has_liked',
            field=models.BooleanField(default=True),
        ),
    ]
