# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0012_auto_20170803_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentlikemodel',
            old_name='has_liked',
            new_name='has_upvoted',
        ),
    ]
