# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0013_auto_20170803_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlikemodel',
            name='has_upvoted',
        ),
        migrations.RemoveField(
            model_name='likemodel',
            name='has_liked',
        ),
        migrations.AlterField(
            model_name='commentlikemodel',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kids.CommentModel'),
        ),
    ]
